### ISSUE TITLE
Best effort stack creation

### ISSUE THREAD

**Issue by KurtStam** [harche/stackup#4]
Feature request:

I'm trying to hook this into our build process to support multiple architectures. At the moment it is a bit of a boot strapping nightmare to create the docker stackup/manifest because the manifest creation will fail if one of the build images is missing. I think it'd be better if a best effort manifest is created and the tool WARNS for missing architectures. This way the manifest creation can run as part of every architecture build and the last one run will update the 'partial' manifest with a full one.

**Comment by harche** [comment]
@KurtStam Thanks for your feedback. We have moved the repo to https://github.com/estesp/manifest-tool for further development of this tool. I will update the README to point towards new repo location. 

I will also raise the issue on that new repo.
